[ENVIRONMENT]
map_yaml = maps/warehouse_map.yaml
# dt in seconds
# How long would one step take in real time
dt = 1.0

max_steps_per_episode = 2000

# Tasks to deliver in one episode
deliveries_per_episode = 10
max_plan_attempts = 6

# downsample map by this factor to speed up path planning
downsample_factor = 3

logging = True

# Extra padding for inflated map
extra_padding = 0.1

# Disable when learning to increase performance
visualize = False

[TASK_ALLOCATION]
logging = False
seed = 42

[ROBOT]
footprint = [[0.75, 0.4], [-0.25, 0.4], [-0.25, -0.40], [0.75, -0.4]]
init_poses = [[11.63, 6.99, -1.7], [11.63, -5.81, 1.7], [-10.77, -4.74, 0.0], [-6.5, 1.12, 0.0], [3.9, -0.05, 3.14]]
distance_tolerance = 0.1
heading_tolerance = 0.1
# For DUBINS path planning
turn_radius = 0.5
logging = False

[COURIER]
logging = False


[LOADER]
init_poses = [[-1.06, -6.88, 1.67], [-0.63, 6.99, -1.67], [4.91, 7.2, -1.67], [4.88, -3.57, 0.0], [-10.77, 6.67, 0.0]]
max_tasks = 5
# seconds
loading_delay = 5
# NOTE does not log anything in current implementatio
logging = True

[UNLOADER]
init_poses = [[13.45, -1.54, 3.14], [13.45, 2.56, 3.14], [-11.83, -6.34, 0.0], [-11.41, 1.23, 0.0], [13.77, 6.99, 3.14]]
# seconds
unloading_delay = 5
# NOTE does not log anything in current implementatio
logging = True